export const testSong = {
    'id': 21,
    'artistId': 11,
    'albumId': 6,
    'name': 'Helpless',
    'musicSrc': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-songs/Crybaby.mp3',
    'waveformImgUrl': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-waveforms/Crybaby.mp3.png',
    'amountOfPlays': 95019,
    'amountOfLikes': 1364,
    'description': 'First song in the album',
    'lyrics': 'Dolorem modi sed amet adipisci. Sed dolorem consectetur numquam aliquam. Dolore quaerat magnam ut sed dolor. Non ut est porro labore quaerat. Adipisci dolorem etincidunt labore etincidunt modi magnam. Ut quisquam modi neque numquam.\n\nNon ipsum amet non eius ut. Tempora non quisquam sit. Dolor quisquam modi sit quisquam est. Modi labore quisquam est porro ipsum quaerat. Sit eius velit labore dolor. Quisquam voluptatem dolore consectetur modi velit velit velit. Numquam porro velit velit modi quaerat. Quiquia etincidunt ipsum dolor dolor. Etincidunt porro quaerat ipsum.\n\nPorro etincidunt sit tempora voluptatem voluptatem. Quiquia modi amet eius. Dolore quisquam etincidunt etincidunt dolorem ipsum quiquia eius. Quaerat quiquia neque sit. Amet eius voluptatem porro quisquam. Velit amet porro non. Non aliquam tempora quisquam eius. Quaerat velit ut porro magnam consectetur.\n\nEst dolore ipsum neque porro ut aliquam dolor. Voluptatem ipsum amet eius quiquia non. Non magnam dolor amet ipsum adipisci quiquia. Modi aliquam est adipisci est etincidunt numquam etincidunt. Eius eius quaerat sed quisquam ipsum modi. Voluptatem dolor porro tempora porro porro amet. Dolore quaerat quisquam magnam. Quaerat voluptatem tempora quisquam etincidunt quisquam consectetur. Sed voluptatem ipsum aliquam porro tempora ut quisquam.',
    'createdDate': '2018-12-04 15:40:51',
    'artist': {
        'id': 11,
        'name': 'We Are All Astronauts',
        'artistDescription': 'Ether is an American producer from Nashville. Ether also produces and posts his songs to his Soundcloud.',
        'createdDate': '2018-12-04 15:40:51',
        'artistImageUrl': 'https://instagram.fktw1-1.fna.fbcdn.net/vp/df0702bb3af8c1581864b98427644d8c/5C8E65A0/t51.2885-15/e35/s320x320/26186297_1144045615726747_3534440781014106112_n.jpg',
    },
    'singer': 'We Are All Astronauts',
    'cover': 'https://picsum.photos/340/340/?v=zyyqei',
    'tags': [{ 'songId': 21, 'songTag': 'Ambient' }],
    'comments': [{
        'id': 82,
        'songId': 21,
        'commentContent': 'Quiquia neque dolor est. Voluptatem quisquam sit dolorem. Sed modi etincidunt ipsum. Ipsum ipsum dolorem magnam tempora. Consectetur magnam labore non porro labore sed. Magnam modi sit amet modi. Non quisquam porro etincidunt adipisci modi tempora. Neque quisquam dolore amet adipisci. Porro est quisquam sed. Magnam velit voluptatem modi amet numquam.',
        'commentAuthorName': 'Lauren Whitaker',
        'createdDate': '2018-12-04 15:40:51',
    }, {
        'id': 81,
        'songId': 21,
        'commentContent': 'Sit ut velit consectetur. Dolorem sed aliquam dolorem eius velit dolor quiquia. Quaerat sit ut dolor. Sed non ut ut magnam. Labore non dolore ut quiquia porro neque. Numquam aliquam modi labore eius modi magnam modi. Labore quaerat dolor tempora. Consectetur etincidunt adipisci tempora voluptatem dolorem amet. Sed ipsum ut ut ipsum porro numquam ipsum.',
        'commentAuthorName': 'Teresa Collins',
        'createdDate': '2018-12-04 15:40:51',
    }, {
        'id': 80,
        'songId': 21,
        'commentContent': 'Amet quaerat est magnam voluptatem velit labore. Dolorem porro aliquam porro dolorem tempora voluptatem ipsum. Amet modi voluptatem porro. Quisquam quaerat ipsum labore numquam. Consectetur aliquam numquam ipsum velit magnam. Dolore porro numquam quiquia velit.',
        'commentAuthorName': 'Mrs. Karen Lambert',
        'createdDate': '2018-12-04 15:40:51',
    }],
};