export const mockAlbum = {
    'id': 1,
    'artistId': 1,
    'albumName': 'Purity',
    'albumDescription': 'Purity is an album by Ether, released at the 10th of June, 2016. It features Jazpe members Lapse and Kaleido.',
    'createdDate': '2018-12-05 18:02:10',
    'artist': {
        'id': 1,
        'name': 'We Are All Astronauts',
        'artistDescription': 'Ether is an American producer from Nashville. Ether also produces and posts his songs to his Soundcloud.',
        'createdDate': '2018-12-05 18:02:10',
        'artistImageUrl': 'https://instagram.fktw1-1.fna.fbcdn.net/vp/df0702bb3af8c1581864b98427644d8c/5C8E65A0/t51.2885-15/e35/s320x320/26186297_1144045615726747_3534440781014106112_n.jpg',
    },
    'songsInsideThisAlbum': [{
        'id': 4,
        'artistId': 1,
        'albumId': 1,
        'name': 'Waves',
        'musicSrc': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-songs/AbsoluteInDoubt.mp3',
        'waveformImgUrl': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-waveforms/AbsoluteInDoubt.mp3.png',
        'amountOfPlays': 30098,
        'amountOfLikes': 4836,
        'description': 'Fourth song in the album',
        'lyrics': 'Tempora aliquam quiquia aliquam. Numquam etincidunt sed non. Consectetur est ut quisquam consectetur voluptatem quaerat neque. Est quisquam quaerat eius labore consectetur dolorem eius. Labore magnam tempora magnam amet etincidunt magnam. Amet amet velit ipsum dolorem non. Adipisci quaerat dolorem dolore dolore etincidunt magnam. Consectetur neque dolor amet magnam etincidunt. Quiquia magnam tempora neque est adipisci. Quiquia voluptatem tempora modi est quisquam porro modi.\n\nNon amet quiquia porro sed est consectetur. Aliquam sit modi magnam. Quiquia quaerat non aliquam numquam. Dolore non est quiquia magnam velit adipisci. Voluptatem dolorem etincidunt porro voluptatem tempora numquam quaerat.\n\nSed amet amet ut numquam ipsum. Ipsum amet sit numquam amet sit est. Etincidunt non quisquam modi est ipsum numquam. Neque etincidunt voluptatem ut tempora etincidunt etincidunt numquam. Tempora quiquia dolorem quiquia quaerat voluptatem voluptatem. Quisquam etincidunt tempora adipisci.',
        'createdDate': '2018-12-05 18:02:10',
        'tags': [{ 'songId': 4, 'songTag': 'Sad' }, { 'songId': 4, 'songTag': 'Dynamic' }],
        'artist': {
            'id': 1,
            'name': 'We Are All Astronauts',
            'artistDescription': 'Ether is an American producer from Nashville. Ether also produces and posts his songs to his Soundcloud.',
            'createdDate': '2018-12-05 18:02:10',
            'artistImageUrl': 'https://instagram.fktw1-1.fna.fbcdn.net/vp/df0702bb3af8c1581864b98427644d8c/5C8E65A0/t51.2885-15/e35/s320x320/26186297_1144045615726747_3534440781014106112_n.jpg',
        },
        'singer': 'We Are All Astronauts',
        'comments': [{
            'id': 17,
            'songId': 4,
            'commentContent': 'Modi quaerat amet quiquia eius sit neque dolore. Labore labore dolorem dolorem numquam dolorem sit neque. Aliquam sed quiquia porro dolorem. Porro amet consectetur modi quiquia ipsum ipsum amet. Sit labore neque quisquam. Aliquam est consectetur tempora neque modi. Ipsum velit aliquam labore velit quiquia porro. Eius modi sit dolore dolore. Velit neque adipisci aliquam porro adipisci velit. Ut dolor quaerat ut ipsum etincidunt velit.',
            'commentAuthorName': 'Sandy Morgan',
            'createdDate': '2018-12-05 18:02:14',
        }, {
            'id': 16,
            'songId': 4,
            'commentContent': 'Sed numquam velit dolore. Ipsum neque adipisci ut est magnam numquam dolore. Amet quisquam sed voluptatem aliquam. Ut etincidunt dolorem adipisci sit voluptatem labore quaerat. Adipisci adipisci magnam amet velit. Non velit ipsum porro est. Sed ipsum porro eius eius dolor numquam.',
            'commentAuthorName': 'Shane Gardner',
            'createdDate': '2018-12-05 18:02:14',
        }, {
            'id': 15,
            'songId': 4,
            'commentContent': 'Quisquam etincidunt amet quiquia eius. Ut dolorem modi magnam aliquam. Ut est sit non ut quaerat. Tempora est quaerat quisquam quisquam sit numquam. Ipsum consectetur est magnam labore. Etincidunt quiquia voluptatem ipsum voluptatem tempora consectetur. Dolorem labore sed dolore quiquia ipsum. Tempora est quiquia eius quisquam. Eius aliquam ut consectetur consectetur velit. Modi etincidunt quiquia modi.',
            'commentAuthorName': 'Tracy George',
            'createdDate': '2018-12-05 18:02:13',
        }, {
            'id': 14,
            'songId': 4,
            'commentContent': 'Modi sit dolorem aliquam ut sed labore. Dolore neque est numquam etincidunt voluptatem. Dolor labore sed porro quisquam dolore. Amet labore non amet est velit labore. Modi tempora consectetur modi amet. Modi porro numquam sit dolore sed. Est eius consectetur consectetur. Amet consectetur dolore amet.',
            'commentAuthorName': 'Daniel Robinson',
            'createdDate': '2018-12-05 18:02:13',
        }],
    }, {
        'id': 3,
        'artistId': 1,
        'albumId': 1,
        'name': 'Awakening',
        'musicSrc': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-songs/Yesterday.mp3',
        'waveformImgUrl': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-waveforms/Yesterday.mp3.png',
        'amountOfPlays': 89505,
        'amountOfLikes': 3414,
        'description': 'Third song in the album',
        'lyrics': 'Sit etincidunt sit adipisci sed modi. Numquam labore non ut. Eius labore velit modi. Neque velit dolor ipsum magnam non. Consectetur velit consectetur quiquia consectetur non. Dolore neque consectetur velit ut quisquam tempora. Est ut quiquia quaerat velit quaerat amet tempora. Adipisci voluptatem tempora magnam porro velit amet sed. Ut ipsum velit dolorem dolor dolore velit sed.\n\nMagnam ipsum labore dolorem ut labore numquam dolor. Ipsum eius velit amet. Sit est aliquam magnam. Porro labore porro sit etincidunt dolorem. Non est adipisci sit sed. Neque quisquam numquam velit voluptatem. Velit non tempora velit numquam dolore.\n\nModi quiquia dolor quaerat quisquam dolore sed eius. Eius tempora quiquia est ut quaerat. Est sit quaerat modi eius voluptatem. Magnam dolore labore quiquia adipisci neque magnam neque. Tempora numquam quaerat velit tempora. Tempora sed etincidunt ut dolor numquam. Ipsum modi labore dolore labore quaerat labore amet.\n\nVelit tempora non aliquam voluptatem. Adipisci quisquam aliquam ipsum. Dolorem sit modi dolor voluptatem. Ut aliquam quisquam dolorem. Ut dolor numquam dolor magnam ipsum consectetur sit. Tempora dolor porro ut. Neque numquam quiquia adipisci labore.',
        'createdDate': '2018-12-05 18:02:10',
        'tags': [{ 'songId': 3, 'songTag': 'Dynamic' }, { 'songId': 3, 'songTag': 'Rock' }],
        'artist': {
            'id': 1,
            'name': 'We Are All Astronauts',
            'artistDescription': 'Ether is an American producer from Nashville. Ether also produces and posts his songs to his Soundcloud.',
            'createdDate': '2018-12-05 18:02:10',
            'artistImageUrl': 'https://instagram.fktw1-1.fna.fbcdn.net/vp/df0702bb3af8c1581864b98427644d8c/5C8E65A0/t51.2885-15/e35/s320x320/26186297_1144045615726747_3534440781014106112_n.jpg',
        },
        'singer': 'We Are All Astronauts',
        'comments': [{
            'id': 13,
            'songId': 3,
            'commentContent': 'Velit amet neque tempora numquam quaerat. Consectetur amet modi dolorem quisquam dolor quiquia dolor. Voluptatem numquam etincidunt magnam dolor quisquam. Modi quiquia porro labore quiquia sit dolor quiquia. Modi dolore modi velit.',
            'commentAuthorName': 'Carolyn Richardson',
            'createdDate': '2018-12-05 18:02:13',
        }, {
            'id': 12,
            'songId': 3,
            'commentContent': 'Neque sit quaerat velit. Labore aliquam velit neque porro sed labore velit. Non neque quaerat quaerat dolore. Dolore quaerat numquam dolor. Aliquam magnam numquam numquam.',
            'commentAuthorName': 'Mary Adams',
            'createdDate': '2018-12-05 18:02:13',
        }, {
            'id': 11,
            'songId': 3,
            'commentContent': 'Quisquam consectetur labore porro dolore sed etincidunt quaerat. Ipsum dolorem dolore voluptatem adipisci dolore dolorem modi. Quaerat magnam porro porro porro quiquia velit dolor. Quisquam sed sit est sit. Eius dolore quaerat etincidunt quiquia amet. Numquam tempora velit numquam amet velit consectetur velit.',
            'commentAuthorName': 'Rachel Parker',
            'createdDate': '2018-12-05 18:02:13',
        }, {
            'id': 10,
            'songId': 3,
            'commentContent': 'Quaerat est dolore neque adipisci sit quiquia. Voluptatem dolorem ipsum adipisci non consectetur quaerat. Ipsum amet est sit neque ipsum. Non modi amet modi labore ipsum velit ipsum. Magnam voluptatem quisquam modi dolor labore.',
            'commentAuthorName': 'Karen Mays',
            'createdDate': '2018-12-05 18:02:13',
        }],
    }, {
        'id': 2,
        'artistId': 1,
        'albumId': 1,
        'name': 'Need a Name',
        'musicSrc': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-songs/LilJeep.mp3',
        'waveformImgUrl': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-waveforms/LilJeep.mp3.png',
        'amountOfPlays': 94729,
        'amountOfLikes': 2694,
        'description': 'Second song in the album',
        'lyrics': 'Dolorem quiquia dolor dolore voluptatem amet. Quaerat velit labore adipisci tempora non quisquam. Sit ut adipisci porro quaerat eius. Voluptatem porro voluptatem magnam dolorem porro. Non consectetur consectetur quiquia. Aliquam adipisci modi amet dolore tempora etincidunt dolor. Non non est velit magnam numquam. Porro magnam magnam sed dolore velit amet.\n\nVoluptatem neque etincidunt neque est voluptatem. Velit aliquam tempora magnam numquam etincidunt. Dolore dolore tempora numquam non. Ut sed dolore porro. Dolor tempora eius quaerat dolorem. Est adipisci neque est tempora. Voluptatem ut consectetur quaerat neque neque consectetur.\n\nQuisquam quaerat adipisci numquam ipsum ipsum. Est sed magnam eius amet sed est etincidunt. Dolorem labore numquam numquam sit labore est. Ipsum dolor sed modi modi velit quaerat sit. Voluptatem aliquam dolore modi porro porro. Quaerat consectetur quiquia tempora dolore eius. Etincidunt est dolorem neque ipsum.',
        'createdDate': '2018-12-05 18:02:10',
        'tags': [{ 'songId': 2, 'songTag': 'Chill' }, { 'songId': 2, 'songTag': 'Ambient' }],
        'artist': {
            'id': 1,
            'name': 'We Are All Astronauts',
            'artistDescription': 'Ether is an American producer from Nashville. Ether also produces and posts his songs to his Soundcloud.',
            'createdDate': '2018-12-05 18:02:10',
            'artistImageUrl': 'https://instagram.fktw1-1.fna.fbcdn.net/vp/df0702bb3af8c1581864b98427644d8c/5C8E65A0/t51.2885-15/e35/s320x320/26186297_1144045615726747_3534440781014106112_n.jpg',
        },
        'singer': 'We Are All Astronauts',
        'comments': [{
            'id': 9,
            'songId': 2,
            'commentContent': 'Quaerat aliquam magnam aliquam. Velit neque sed amet. Dolore numquam tempora quisquam numquam sit quiquia porro. Tempora ipsum quisquam dolorem quisquam. Est dolor adipisci sed etincidunt. Dolor tempora dolore sed amet. Quaerat ut eius porro est magnam ipsum ipsum. Quiquia etincidunt est adipisci quiquia tempora dolor voluptatem. Ut modi quisquam amet consectetur dolore ipsum.',
            'commentAuthorName': 'Brad Holden',
            'createdDate': '2018-12-05 18:02:13',
        }, {
            'id': 8,
            'songId': 2,
            'commentContent': 'Quaerat voluptatem labore consectetur ut adipisci magnam eius. Non dolorem quiquia dolorem quaerat porro dolor porro. Quiquia velit velit voluptatem ipsum dolorem. Labore ut sed labore non. Magnam numquam amet amet sed. Porro quisquam est amet.',
            'commentAuthorName': 'Joel Tanner',
            'createdDate': '2018-12-05 18:02:13',
        }, {
            'id': 7,
            'songId': 2,
            'commentContent': 'Modi eius porro voluptatem sed eius neque magnam. Quiquia est labore tempora non. Labore quisquam amet consectetur quiquia. Labore sit sit quaerat. Tempora quaerat ut dolore velit sit consectetur. Quisquam voluptatem sit eius etincidunt sit quisquam. Ut velit consectetur magnam voluptatem amet.',
            'commentAuthorName': 'Erin Richards',
            'createdDate': '2018-12-05 18:02:12',
        }, {
            'id': 6,
            'songId': 2,
            'commentContent': 'Dolor adipisci dolor voluptatem dolorem amet quiquia adipisci. Modi aliquam magnam velit velit. Labore adipisci dolore etincidunt non ipsum. Adipisci est dolor tempora. Sit sed quiquia tempora neque porro. Sit quiquia eius amet amet voluptatem. Modi sed tempora velit ut ut modi est. Porro sit consectetur sed. Non sed tempora est.',
            'commentAuthorName': 'Julie Reid',
            'createdDate': '2018-12-05 18:02:12',
        }, {
            'id': 5,
            'songId': 2,
            'commentContent': 'Numquam quisquam dolorem porro etincidunt. Est adipisci dolore modi velit etincidunt. Dolor dolorem dolore neque est. Aliquam quiquia porro adipisci velit consectetur etincidunt amet. Porro dolore est quisquam. Est ut neque sit dolore numquam dolor amet. Voluptatem non ipsum sit modi etincidunt quiquia dolore. Modi porro voluptatem neque sed modi eius. Quaerat porro amet numquam porro ipsum quaerat.',
            'commentAuthorName': 'Kevin Jones',
            'createdDate': '2018-12-05 18:02:12',
        }],
    }, {
        'id': 1,
        'artistId': 1,
        'albumId': 1,
        'name': 'Helpless',
        'musicSrc': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-songs/Crybaby.mp3',
        'waveformImgUrl': 'https://s3-eu-west-1.amazonaws.com/melody-cloud-waveforms/Crybaby.mp3.png',
        'amountOfPlays': 25145,
        'amountOfLikes': 2158,
        'description': 'First song in the album',
        'lyrics': 'Quaerat dolore non sit sit sed numquam est. Numquam quisquam tempora ipsum. Quaerat quisquam tempora etincidunt quisquam est quisquam. Aliquam dolorem dolore quaerat velit porro dolorem. Quiquia consectetur eius quaerat consectetur velit labore. Etincidunt tempora est dolorem neque ipsum. Non adipisci velit quiquia porro. Amet neque voluptatem non non ut dolore porro.\n\nMagnam dolore magnam eius etincidunt. Eius etincidunt amet magnam porro dolore dolorem voluptatem. Quisquam etincidunt est modi. Est aliquam sed porro non dolor tempora. Ipsum ut labore amet quiquia consectetur quiquia. Eius dolorem velit labore sed consectetur consectetur. Quaerat labore sit eius non amet non aliquam. Labore eius dolore amet eius eius porro voluptatem. Amet adipisci tempora consectetur ipsum adipisci numquam magnam.\n\nNeque dolore eius dolor voluptatem aliquam sed. Sit amet ut dolore etincidunt neque. Magnam etincidunt amet eius. Adipisci amet labore quaerat velit dolore. Sit modi etincidunt aliquam dolor ut magnam labore. Dolorem dolore velit sed.\n\nDolorem sed consectetur dolor est. Sed quaerat dolorem etincidunt. Dolor porro quaerat labore. Voluptatem modi modi labore quisquam ipsum ipsum aliquam. Aliquam aliquam amet dolor est amet eius.\n\nUt voluptatem amet aliquam velit eius quaerat neque. Consectetur quiquia dolor labore voluptatem porro. Etincidunt quaerat etincidunt sed sit aliquam numquam. Modi porro dolorem velit magnam velit numquam adipisci. Tempora sit consectetur sit est dolore modi amet. Sit modi adipisci sed est dolor adipisci. Non porro magnam modi. Ut sit sed modi.\n\nIpsum amet voluptatem dolorem eius. Sit voluptatem velit quiquia quisquam. Quaerat ipsum quiquia adipisci modi. Velit eius dolore sit aliquam. Dolore amet adipisci voluptatem ipsum. Dolorem modi quisquam eius est ipsum labore. Sit etincidunt consectetur neque velit numquam ipsum aliquam.',
        'createdDate': '2018-12-05 18:02:10',
        'tags': [{ 'songId': 1, 'songTag': 'Ambient' }],
        'artist': {
            'id': 1,
            'name': 'We Are All Astronauts',
            'artistDescription': 'Ether is an American producer from Nashville. Ether also produces and posts his songs to his Soundcloud.',
            'createdDate': '2018-12-05 18:02:10',
            'artistImageUrl': 'https://instagram.fktw1-1.fna.fbcdn.net/vp/df0702bb3af8c1581864b98427644d8c/5C8E65A0/t51.2885-15/e35/s320x320/26186297_1144045615726747_3534440781014106112_n.jpg',
        },
        'singer': 'We Are All Astronauts',
        'comments': [{
            'id': 4,
            'songId': 1,
            'commentContent': 'Dolorem quisquam velit dolorem dolorem. Tempora ut quisquam dolor labore sed porro magnam. Porro amet neque magnam etincidunt etincidunt. Quisquam non amet ut quiquia est dolore. Magnam sit quisquam ipsum sed dolor eius. Dolore consectetur tempora sit.',
            'commentAuthorName': 'Angela Young MD',
            'createdDate': '2018-12-05 18:02:12',
        }, {
            'id': 3,
            'songId': 1,
            'commentContent': 'Amet quisquam sit aliquam dolorem ut. Ipsum quisquam non adipisci modi quiquia. Aliquam consectetur adipisci consectetur numquam quiquia. Voluptatem sed quaerat ipsum quiquia. Amet etincidunt non labore sed non quaerat etincidunt.',
            'commentAuthorName': 'Geoffrey Martinez',
            'createdDate': '2018-12-05 18:02:12',
        }, {
            'id': 2,
            'songId': 1,
            'commentContent': 'Sed est magnam adipisci eius numquam dolore quisquam. Magnam ut modi modi. Ut quisquam consectetur labore non. Labore quiquia consectetur dolorem velit quaerat numquam. Neque etincidunt consectetur amet modi ipsum adipisci aliquam.',
            'commentAuthorName': 'Mark Gonzalez',
            'createdDate': '2018-12-05 18:02:12',
        }, {
            'id': 1,
            'songId': 1,
            'commentContent': 'Velit quisquam sit dolore modi ipsum neque dolorem. Dolorem consectetur quisquam dolore non numquam. Quisquam quaerat numquam aliquam. Modi adipisci modi dolorem est modi modi. Neque eius quaerat ut. Voluptatem voluptatem quisquam sed non voluptatem magnam modi. Est est dolorem quisquam quiquia voluptatem magnam labore. Dolor quiquia quisquam adipisci. Dolore quiquia velit dolore tempora amet.',
            'commentAuthorName': 'Alec Blackwell',
            'createdDate': '2018-12-05 18:02:12',
        }],
    }],
};