export const Views = {
    SONGS_FEED: 'SONGS_FEED',
    SONG_DETAILS: 'SONG_DETAILS',
    ARTIST_DETAILS: 'ARTIST_DETAILS',
    ALBUM_DETAILS: 'ALBUM_DETAILS',
    EXPLORE_NEW_ALBUMS: 'EXPLORE_NEW_ALBUMS',
    PLAYLIST_VIEW: 'PLAYLIST_VIEW',
};

